### ISSUE TITLE
--es-module-specifier-resolution has renamed to --experimental-specifier-resolution

### ISSUE THREAD

**Issue by Trendymen** [Urigo/typescript-node-es-modules-example#24]
--es-module-specifier-resolution has renamed to --experimental-specifier-resolution.
Please consider to change the Readme.md. Because i can't find the ```--es-module-specifier-resolution```in nodejs documents....

**Comment by Urigo** [comment]
You are right!
It still supported the old syntax but it's better to update.
I've updated the example.
Thank you for pointing that out
